# Generated by Django 4.0.2 on 2022-03-07 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_location_alter_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='social_likedin',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
