# Generated by Django 4.0.2 on 2022-03-07 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_social_likedin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='social_likedin',
            new_name='social_linkedin',
        ),
    ]
